# Generated by Django 5.2.8 on 2025-11-21 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('source_language', models.CharField(max_length=50)),
                ('target_language', models.CharField(max_length=50)),
                ('source_file_path', models.FileField(upload_to='translations/source/')),
                ('translated_file_path', models.FileField(blank=True, null=True, upload_to='translations/translated/')),
                ('status', models.CharField(choices=[('Yangi', 'Yangi'), ('Jarayonda', 'Jarayonda'), ('Bajarildi', 'Bajarildi'), ('BekorQilindi', 'Bekor Qilindi')], default='Yangi', max_length=20)),
                ('word_count', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
    ]
