# Generated by Django 6.0.2 on 2026-10-07 11:29

import config.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationrequest',
            name='source_file_path',
            field=models.FileField(upload_to=config.uploads.RandomizedUploadPath('translations/source')),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='translated_file_path',
            field=models.FileField(blank=True, null=True, upload_to=config.uploads.RandomizedUploadPath('translations/translated')),
        ),
    ]
