# Generated by Django 5.0.1 on 2026-03-09 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_transaction_extra_data_udk_request'),
        ('udc', '0002_seed_udk_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UDKCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('udk_code', models.CharField(max_length=50)),
                ('udk_description', models.TextField(blank=True)),
                ('certificate_path', models.FileField(blank=True, null=True, upload_to='udc/certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='udk_certificate', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udk_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "UDK ma'lumotnoma (standalone)",
                'verbose_name_plural': "UDK ma'lumotnomalar (standalone)",
                'ordering': ['-created_at'],
            },
        ),
    ]
