# Generated by Django 5.0.1 on 2026-03-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udc', '0003_udk_certificate_standalone'),
    ]

    operations = [
        migrations.AddField(
            model_name='udkcertificate',
            name='author_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
