# Generated by Django 5.0.1 on 2026-03-13 00:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_doi_request'),
        ('udc', '0004_add_author_name_to_udk_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UdkRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_first_name', models.CharField(max_length=150)),
                ('author_last_name', models.CharField(max_length=150)),
                ('author_middle_name', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='udk_requests/%Y/%m/')),
                ('udk_code', models.CharField(blank=True, max_length=100)),
                ('udk_description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending_payment', "To'lov kutilmoqda"), ('submitted', 'Taqrizchida'), ('completed', 'Yakunlangan'), ('rejected', 'Rad etilgan')], default='pending_payment', max_length=30)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='udk_request', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udk_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "UDK so'rovi",
                'verbose_name_plural': "UDK so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
