# Generated by Django 6.0.2 on 2026-10-07 11:29

import config.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udc', '0008_translation_per_word_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udkrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=config.uploads.RandomizedUploadPath('udk_requests')),
        ),
    ]
