# Generated by Django 6.0.2 on 2026-02-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('status_change', "Status o'zgarishi"), ('review_assigned', 'Taqriz tayinlandi'), ('review_completed', 'Taqriz yakunlandi'), ('payment', "To'lov"), ('plagiarism', 'Antiplagiat'), ('system', 'Tizim'), ('article', 'Maqola')], default='system', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Bildirishnoma', max_length=255),
        ),
    ]
