# Generated by Django 5.2.8 on 2025-11-21 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_number', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='issues/')),
                ('collection_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('issn', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('rules', models.TextField(blank=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='journals/')),
                ('payment_model', models.CharField(choices=[('pre-payment', 'Pre-Payment'), ('post-payment', 'Post-Payment')], default='pre-payment', max_length=20)),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('per_page', 'Per Page')], default='fixed', max_length=20)),
                ('publication_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_page', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_doc_required', models.BooleanField(default=False)),
                ('additional_doc_label', models.CharField(blank=True, max_length=200)),
                ('additional_doc_type', models.CharField(choices=[('file', 'File'), ('link', 'Link')], default='file', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Journal Categories',
            },
        ),
    ]
