# Generated by Django 5.2.8 on 2025-11-21 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='journals.journal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='journals.journalcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('journal', 'issue_number')},
        ),
    ]
