# Generated by Django 6.0.2 on 2026-02-19 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scientific Field',
                'verbose_name_plural': 'Scientific Fields',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.journalcategory')),
                ('scientific_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.scientificfield')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AuthorPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('publication_type', models.CharField(choices=[('journal_local', 'Mahalliy OAK jurnali'), ('journal_international', 'Xalqaro OAK jurnali'), ('journal_local_general', 'Mahalliy jurnal'), ('journal_international_general', 'Xalqaro jurnal'), ('conference_local', 'Mahalliy konferensiya'), ('conference_international', 'Xalqaro konferensiya'), ('scopus_journal', 'Scopus jurnali'), ('scopus_conference', 'Scopus konferensiyasi')], max_length=30)),
                ('publication_date', models.DateField()),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('co_authors', models.TextField(blank=True, help_text='Mualliflar vergul bilan ajratilgan')),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text="Kalit so'zlar vergul bilan ajratilgan")),
                ('file_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journals.journal')),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journals.conference')),
                ('scientific_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.scientificfield')),
            ],
            options={
                'verbose_name': 'Author Publication',
                'verbose_name_plural': 'Author Publications',
                'ordering': ['-publication_date', 'title'],
            },
        ),
    ]
