# Generated by Django 6.0.2 on 2026-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_scientificfield_conference_authorpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='ai_content_max_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='originality_min_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='plagiarism_max_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
