# Generated by Django 5.2.8 on 2025-11-21 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='patronymic')),
                ('role', models.CharField(choices=[('author', 'Author'), ('reviewer', 'Reviewer'), ('journal_admin', 'Journal Admin'), ('super_admin', 'Super Admin'), ('accountant', 'Accountant')], default='author', max_length=20, verbose_name='role')),
                ('orcid_id', models.CharField(blank=True, max_length=50, verbose_name='ORCID ID')),
                ('affiliation', models.CharField(max_length=255, verbose_name='affiliation')),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='telegram username')),
                ('gamification_level', models.CharField(default='Beginner', max_length=50, verbose_name='level')),
                ('gamification_badges', models.JSONField(default=list, verbose_name='badges')),
                ('gamification_points', models.IntegerField(default=0, verbose_name='points')),
                ('specializations', models.JSONField(blank=True, default=list, verbose_name='specializations')),
                ('reviews_completed', models.IntegerField(default=0, verbose_name='reviews completed')),
                ('average_review_time', models.FloatField(default=0, verbose_name='average review time (days)')),
                ('acceptance_rate', models.FloatField(default=0, verbose_name='acceptance rate (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
