# Generated by Django 6.0.2 on 2026-10-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('reviewer', 'Reviewer'), ('journal_admin', 'Journal Admin'), ('super_admin', 'Super Admin'), ('accountant', 'Accountant'), ('operator', 'Operator')], default='author', max_length=20, verbose_name='role'),
        ),
    ]
