# Generated by Django 6.0.2 on 2026-10-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_choices_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_notifications',
            field=models.BooleanField(default=True, verbose_name='telegram notifications'),
        ),
    ]
