# Generated by Django 6.0.2 on 2026-10-10 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_telegram_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='phone verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='phone verified at'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='terms accepted at'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='terms version'),
        ),
        migrations.CreateModel(
            name='PhoneChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('verify', 'Telefonni tasdiqlash'), ('reset', 'Parolni tiklash'), ('reset_link', 'Parolni tiklash havolasi')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telefon tasdiqlash kodi',
                'verbose_name_plural': 'Telefon tasdiqlash kodlari',
                'indexes': [models.Index(fields=['purpose', 'created_at'], name='users_phone_purpose_063420_idx')],
            },
        ),
    ]
