# Generated by Django 5.2.8 on 2025-11-21 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('Draft', 'Qoralama'), ('Yangi', 'Yangi'), ('WithEditor', 'Redaktorda'), ('QabulQilingan', 'Qabul Qilingan'), ('WritingInProgress', 'Yozish jarayonida'), ('NashrgaYuborilgan', 'Nashrga Yuborilgan'), ('Revision', 'Tahrirga qaytarilgan'), ('Accepted', 'Qabul qilingan'), ('Rejected', 'Rad etilgan'), ('Published', 'Nashr etilgan')], default='Draft', max_length=50)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0)),
                ('downloads_count', models.IntegerField(default=0)),
                ('citations_count', models.IntegerField(default=0)),
                ('certificate_url', models.CharField(blank=True, max_length=500)),
                ('publication_url', models.CharField(blank=True, max_length=500)),
                ('publication_certificate_url', models.CharField(blank=True, max_length=500)),
                ('thesis_url', models.CharField(blank=True, max_length=500)),
                ('final_pdf_path', models.FileField(blank=True, null=True, upload_to='articles/pdfs/')),
                ('additional_document_path', models.FileField(blank=True, null=True, upload_to='articles/additional/')),
                ('review_content', models.TextField(blank=True)),
                ('page_count', models.IntegerField(default=0)),
                ('fast_track', models.BooleanField(default=False)),
                ('plagiarism_percentage', models.FloatField(default=0)),
                ('ai_content_percentage', models.FloatField(default=0)),
                ('plagiarism_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('file_path', models.FileField(upload_to='articles/versions/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('digital_hash', models.CharField(blank=True, max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
    ]
