# Generated by Django 6.0.2 on 2026-02-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='plagiarism_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Qoralama'), ('Yangi', 'Yangi'), ('WithEditor', 'Redaktorda'), ('QabulQilingan', 'Qabul Qilingan'), ('WritingInProgress', 'Yozish jarayonida'), ('NashrgaYuborilgan', 'Nashrga Yuborilgan'), ('Revision', 'Tahrirga qaytarilgan'), ('Accepted', 'Qabul qilingan'), ('Rejected', 'Rad etilgan'), ('Published', 'Nashr etilgan'), ('ContractProcessing', 'Shartnoma rasmiylashtirilmoqda'), ('IsbnProcessing', 'ISBN olinmoqda'), ('AuthorDataVerified', 'Muallif ma`lumotlari tasdiqlandi'), ('PaymentCompleted', 'To`lov jarayoni yakunlandi'), ('SentToPrint', 'Bosmaga berildi'), ('Printing', 'Chop etilmoqda'), ('Ready', 'Tayyor'), ('Packaging', 'Qadoqlanmoqda'), ('Shipping', 'Yuborilmoqda (pochta)'), ('Delivered', 'Yetkazildi'), ('ProcessPaused', 'Jarayon to`xtatildi')], default='Draft', max_length=50),
        ),
    ]
