# Generated by Django 5.0.1 on 2026-03-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_add_plagiarism_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='udk_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='udk_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
