# Generated by Django 5.0.1 on 2026-03-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_udk_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='udk_certificate_path',
            field=models.FileField(blank=True, null=True, upload_to='articles/udk_certificates/'),
        ),
    ]
