# Generated by Django 5.0.1 on 2026-03-09 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_udk_certificate'),
        ('payments', '0010_article_sample_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSampleRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirements', models.TextField(help_text="Maqola bo'yicha talablar")),
                ('pages', models.PositiveIntegerField(default=1)),
                ('topic', models.CharField(max_length=500)),
                ('quality_level', models.CharField(choices=[('quyi', 'Quyi sifatli'), ('orta', "O'rta sifatli"), ('yuqori', 'Yuqori sifatli')], max_length=20)),
                ('author_first_name', models.CharField(max_length=150)),
                ('author_last_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_sample_request', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_sample_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Maqola namuna so'rovi",
                'verbose_name_plural': "Maqola namuna so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
