# Generated by Django 5.0.1 on 2026-03-09 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_sample_request'),
        ('payments', '0011_doi_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoiRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_first_name', models.CharField(max_length=150)),
                ('author_last_name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='doi_requests/%Y/%m/')),
                ('status', models.CharField(choices=[('pending_payment', "To'lov kutilmoqda"), ('submitted', 'Taqrizchida'), ('completed', 'Yakunlangan')], default='pending_payment', max_length=30)),
                ('doi_link', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doi_request', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doi_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "DOI so'rovi",
                'verbose_name_plural': "DOI so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
