# Generated by Django 6.0.2 on 2026-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_doi_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='originality_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Qoralama'), ('Yangi', 'Yangi'), ('WithEditor', 'Redaktorda'), ('QabulQilingan', 'Qabul Qilingan'), ('WritingInProgress', 'Yozish jarayonida'), ('NashrgaYuborilgan', 'Nashrga Yuborilgan'), ('PlagiarismReview', "Antiplagiat ko'rib chiqish (bosh admin qarori)"), ('Revision', 'Tahrirga qaytarilgan'), ('Accepted', 'Qabul qilingan'), ('Rejected', 'Rad etilgan'), ('Published', 'Nashr etilgan'), ('ContractProcessing', 'Shartnoma rasmiylashtirilmoqda'), ('IsbnProcessing', 'ISBN olinmoqda'), ('AuthorDataVerified', 'Muallif ma`lumotlari tasdiqlandi'), ('PaymentCompleted', 'To`lov jarayoni yakunlandi'), ('SentToPrint', 'Bosmaga berildi'), ('Printing', 'Chop etilmoqda'), ('Ready', 'Tayyor'), ('Packaging', 'Qadoqlanmoqda'), ('Shipping', 'Yuborilmoqda (pochta)'), ('Delivered', 'Yetkazildi'), ('ProcessPaused', 'Jarayon to`xtatildi')], default='Draft', max_length=50),
        ),
    ]
