# Generated by Django (article issue + publication certificate file)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
        ('articles', '0008_plagiarism_ai_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journals.Issue'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_certificate_path',
            field=models.FileField(blank=True, null=True, upload_to='articles/publication_certificates/'),
        ),
    ]
