# Generated by Django 5.2.12 on 2026-04-10 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_issue_publication_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleOperatorMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_messages', to='articles.article')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_operator_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maqola — operator chati xabari',
                'verbose_name_plural': 'Maqola — operator chati xabarlari',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['article', 'created_at'], name='articles_ar_article_8d4809_idx')],
            },
        ),
    ]
