# Generated by Django 6.0.2 on 2026-10-07 11:29

import config.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_antiplag_corpus_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='additional_document_path',
            field=models.FileField(blank=True, null=True, upload_to=config.uploads.RandomizedUploadPath('articles/additional')),
        ),
        migrations.AlterField(
            model_name='article',
            name='final_pdf_path',
            field=models.FileField(blank=True, null=True, upload_to=config.uploads.RandomizedUploadPath('articles/pdfs')),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='file_path',
            field=models.FileField(upload_to=config.uploads.RandomizedUploadPath('articles/versions')),
        ),
        migrations.AlterField(
            model_name='doirequest',
            name='file',
            field=models.FileField(upload_to=config.uploads.RandomizedUploadPath('doi_requests')),
        ),
    ]
