# Generated by Django 6.0.2 on 2026-10-08 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
import re

from django.db import migrations, models

_CHANGED_RE = re.compile(r'^Status changed from (\S+) to (\S+)$')


def backfill_status_events(apps, schema_editor):
    """Mavjud maqolalar uchun tarixni ActivityLog yozuvlaridan tiklash."""
    Article = apps.get_model('articles', 'Article')
    ActivityLog = apps.get_model('articles', 'ActivityLog')
    Event = apps.get_model('articles', 'ArticleStatusEvent')

    for article in Article.objects.all().only('id', 'status', 'submission_date').iterator():
        transitions = []
        logs = ActivityLog.objects.filter(article_id=article.id).order_by('timestamp')
        for log in logs.iterator():
            action = (log.action or '').strip()
            m = _CHANGED_RE.match(action)
            if m:
                transitions.append((m.group(1), m.group(2), log.user_id, log.details or '', log.timestamp))
            elif action.startswith('Status: NashrgaYuborilgan') and 'Rejected' in action:
                transitions.append(('NashrgaYuborilgan', 'Rejected', log.user_id, log.details or '', log.timestamp))
            elif action.startswith("Status: Antiplagiat ko'rib chiqish"):
                transitions.append(('NashrgaYuborilgan', 'PlagiarismReview', log.user_id, log.details or '', log.timestamp))
            elif action.startswith('Nashr qilindi'):
                transitions.append(('Accepted', 'Published', log.user_id, '', log.timestamp))

        if transitions:
            initial = transitions[0][0]
        else:
            initial = article.status if article.status in ('Draft', 'Yangi') else 'Yangi'

        rows = [('', initial, None, '', article.submission_date)] + transitions
        if not transitions and article.status != initial:
            # Oraliq yozuvlar yo'q — joriy holatni sanasiz emas, yuborilgan sana bilan qo'yamiz.
            rows.append((initial, article.status, None, '', article.submission_date))

        for from_s, to_s, user_id, note, when in rows:
            ev = Event.objects.create(
                article_id=article.id,
                from_status=from_s or '',
                to_status=to_s,
                actor_id=user_id,
                note=(note or '')[:2000],
            )
            if when:
                Event.objects.filter(pk=ev.pk).update(created_at=when)


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_private_upload_paths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_status_events', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='articles.article')),
            ],
            options={
                'verbose_name': 'Maqola holati tarixi',
                'verbose_name_plural': 'Maqola holati tarixi',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['article', 'created_at'], name='articles_ar_article_09678d_idx')],
            },
        ),
        migrations.RunPython(backfill_status_events, migrations.RunPython.noop),
    ]
