# Generated by Django 6.0.2 on 2026-10-08 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_article_status_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiplagIndexedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_key', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('article', 'Platforma maqolasi'), ('corpus', 'Arxiv / import'), ('check', 'Mustaqil tekshiruv (maxfiy)'), ('meta', 'Xizmat yozuvi')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('is_public', models.BooleanField(default=False)),
                ('author_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('text', models.TextField(blank=True)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Antiplagiat indeksidagi hujjat',
                'verbose_name_plural': 'Antiplagiat indeksidagi hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='AntiplagFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.BigIntegerField(db_index=True)),
                ('position', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='articles.antiplagindexeddocument')),
            ],
            options={
                'verbose_name': 'Antiplagiat barmoq izi',
                'verbose_name_plural': 'Antiplagiat barmoq izlari',
            },
        ),
    ]
