# Generated by Django 6.0.2 on 2026-10-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_antiplag_fingerprint_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiplagcorpusdocument',
            name='fulltext_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AntiplagHarvestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('set_spec', models.CharField(blank=True, default='', max_length=200)),
                ('last_datestamp', models.CharField(blank=True, default='', max_length=40)),
                ('completed', models.BooleanField(default=False)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': "OAI yig'ish holati",
                'verbose_name_plural': "OAI yig'ish holatlari",
                'unique_together': {('endpoint', 'set_spec')},
            },
        ),
    ]
