# Generated by Django 5.2.8 on 2025-11-21 22:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('review_content', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0)),
                ('review_type', models.CharField(choices=[('open', 'Open'), ('single_blind', 'Single Blind'), ('double_blind', 'Double Blind')], default='double_blind', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='articles.article')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
