# Generated by Django 6.0.2 on 2026-02-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreview',
            name='clarity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='comments_to_author',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='comments_to_editor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='methodology_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='originality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('accept', 'Qabul qilish'), ('minor_revision', 'Kichik tuzatish'), ('major_revision', 'Katta tuzatish'), ('reject', 'Rad etish')], max_length=20),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='references_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='significance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='weaknesses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='peerreview',
            name='review_type',
            field=models.CharField(choices=[('open', 'Ochiq'), ('single_blind', 'Bir tomonlama'), ('double_blind', 'Ikki tomonlama')], default='double_blind', max_length=20),
        ),
        migrations.AlterField(
            model_name='peerreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('declined', 'Rad etildi'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlandi')], default='pending', max_length=20),
        ),
    ]
