# Generated by Django 5.2.8 on 2025-11-21 22:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('service_type', models.CharField(choices=[('fast-track', 'Fast Track'), ('publication_fee', 'Publication Fee'), ('language_editing', 'Language Editing'), ('top_up', 'Top Up'), ('book_publication', 'Book Publication'), ('translation', 'Translation')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('click_trans_id', models.CharField(blank=True, max_length=100)),
                ('click_paydoc_id', models.CharField(blank=True, max_length=100)),
                ('merchant_trans_id', models.CharField(blank=True, max_length=100)),
                ('receipt_path', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='articles.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
