# Generated by Django 5.2.8 on 2025-11-21 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='translation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='translations.translationrequest'),
        ),
    ]
