# Generated by Django 5.2.8 on 2025-11-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
    ]
