# Generated by Django 5.2.8 on 2025-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20251124_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text="To'lov tavsifi"),
        ),
    ]
