# Generated by Django 5.2.8 on 2025-12-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
    ]
