# Generated by Django 6.0.2 on 2026-02-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='click_service_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payme_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payme_trans_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_provider',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
