# Generated by Django 5.0.1 on 2026-03-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_transaction_click_service_id_transaction_payme_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='error_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
