# Generated by Django 5.0.1 on 2026-03-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_transaction_error_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service_type',
            field=models.CharField(choices=[('fast-track', 'Fast Track'), ('publication_fee', 'Publication Fee'), ('language_editing', 'Language Editing'), ('top_up', 'Top Up'), ('book_publication', 'Book Publication'), ('translation', 'Translation'), ('udk_request', "UDK so'rov / Tasdiqlangan ma'lumotnoma")], max_length=50),
        ),
    ]
