# Generated by Django 5.0.1 on 2026-03-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_transaction_extra_data_udk_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service_type',
            field=models.CharField(choices=[('fast-track', 'Fast Track'), ('publication_fee', 'Publication Fee'), ('language_editing', 'Language Editing'), ('top_up', 'Top Up'), ('book_publication', 'Book Publication'), ('translation', 'Translation'), ('udk_request', "UDK so'rov / Tasdiqlangan ma'lumotnoma"), ('article_sample', 'Maqola namuna olish (taqrizchiga yuborish)')], max_length=50),
        ),
    ]
