# Generated by Django 6.0.2 on 2026-10-07 11:29

import config.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_doi_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_path',
            field=models.FileField(blank=True, null=True, upload_to=config.uploads.RandomizedUploadPath('receipts')),
        ),
    ]
