"""Saytdagi SubmitArticle filtrlari bilan bir xil kategoriyalar."""

PUBLICATION_TYPES = [
    'Mahalliy OAK jurnallari',
    'Xalqaro OAK jurnallari',
    'Mahalliy jurnallar',
    'Xalqaro jurnallar',
    'Mahalliy konferensiyalar',
    'Xalqaro konferensiyalar',
    'Scopus jurnallari',
    'Scopus konferensiyalar',
]

SUBJECT_AREAS = [
    'Pedagogika va ta\'lim',
    'Psixologiya',
    'Filologiya va tilshunoslik',
    'Tarix',
    'Falsafa',
    'Iqtisodiyot',
    'Menejment va biznes',
    'Huquq',
    'Siyosatshunoslik',
    'Sotsiologiya',
    'Axborot texnologiyalari (IT)',
    'Matematika',
    'Fizika',
    'Kimyo',
    'Biologiya',
    'Tibbiyot',
    'Qishloq xo\'jaligi',
    'Arxitektura va qurilish',
    'Transport va logistika',
    'San\'at va madaniyat',
    'Jurnalistika va ommaviy kommunikatsiya',
    'Turizm va mehmondo\'stlik',
    'Sport va jismoniy tarbiya',
    'Ekologiya va atrof-muhit muhofazasi',
    'Texnika fanlari',
    'Energetika',
    'Harbiy fanlar va xavfsizlik',
    'Dinshunoslik',
    'Gender tadqiqotlari',
    'Multidissiplinar (fanlararo) yo\'nalishlar',
]
